blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

urlpatterns = [
    # path('', views.post_list, name='post_list'),
    path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<str:post>',
         views.PostDetailView.as_view(), name='post_detail'),
    path('<pk>/share/', views.PostShareView.as_view(), name='post_share'),
    path('tag/<str:tag_slug>/', views.PostListView.as_view(), name='post_list_by_tag'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.PostSearchView.as_view(), name='post_search'),
]

blog_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.views.generic.base import RedirectView

sitemaps = {'posts': PostSitemap}

urlpatterns = [
    path('admin/', admin.site.urls),
                  path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
                  path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
                  path('', RedirectView.as_view(pattern_name='blog:post_list', permanent=False))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, related_name='blog_posts', on_delete=models.CASCADE)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])

    objects = models.Manager()
    published = PublishedManager()


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea(attrs={'rows': 4}))
    bot_catcher = forms.CharField(required=False, widget=forms.HiddenInput)


class CommentForm(forms.ModelForm):
    body = forms.CharField(required=False, widget=forms.Textarea(attrs={'rows': 4}))

    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
# from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView, DetailView, TemplateView
from .models import Post
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 4
    template_name = 'blog/post/list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tag = None

        if 'tag_slug' in self.kwargs:
            tag = get_object_or_404(Tag, slug=self.kwargs['tag_slug'])
            context['posts'] = self.queryset.filter(tags__in=[tag])

        context['tag'] = tag
        return context


class PostDetailView(DetailView):
    template_name = 'blog/post/detail.html'
    context_object_name = 'post'
    model = None

    def dispatch(self, request, *args, **kwargs):
        self.model = get_object_or_404(Post, slug=self.kwargs['post'], status='published',
                                       publish__year=self.kwargs['year'],
                                       publish__month=self.kwargs['month'],
                                       publish__day=self.kwargs['day'])
        comments = self.model.comments.filter(active=True)
        post_tags_ids = self.model.tags.values_list('id', flat=True)
        similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(pk=self.model.pk)
        similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]

        if request.method == 'POST':
            new_comment = True
            comment_form = CommentForm(data=request.POST)
            if comment_form.is_valid():
                new_comment = comment_form.save(commit=False)
                new_comment.post = self.model
                new_comment.save()
        else:
            new_comment = None
            comment_form = CommentForm()
        return self.render_to_response({'post': self.model, 'comments': comments, 'comment_form': comment_form,
                                        'similar_posts': similar_posts, 'new_comment': new_comment})


class PostShareView(DetailView):
    template_name = 'blog/post/share.html'
    model = Post
    context_object_name = 'post'
    sent = False
    cd = {}

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(status='published')

    def post(self, request, *args, **kwargs):
        form = EmailPostForm(request.POST)
        post = self.get_object()
        if form.is_valid():
            self.cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f'{self.cd["name"]} ({self.cd["email"]}) recommends you reading "{post.title}"'
            message = f'Read "{post.title}" at {post_url}\n\n{self.cd["name"]}\'s comments: {self.cd["comments"]}'
            send_mail(subject, message, 'admin@myblog.com', [self.cd['to']])
            self.sent = True
        return self.render_to_response({'post': self.get_object(), 'form': form, 'sent': self.sent, 'cd': self.cd})

    def get(self, request, *args, **kwargs):
        form = EmailPostForm()
        return self.render_to_response({'post': self.get_object(), 'form': form, 'sent': self.sent, 'cd': self.cd})


class PostSearchView(TemplateView):
    template_name = 'blog/post/search.html'

    def post(self, request, *args, **kwargs):
        if request.POST['phrase']:
            phrase = request.POST['phrase']
            searched_posts = [post for post in Post.published.all() if
                              phrase in post.body.lower() or phrase in post.title]
            total_results = len(searched_posts)
        else:
            return redirect('blog:post_list')
        return self.render_to_response(
            {'phrase': phrase, 'searched_posts': searched_posts, 'total_results': total_results})

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
{% load blog_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "css/bootstrap/css/bootstrap.css" %}" rel="stylesheet">
    <link href="{% static "css/blog.css" %}" rel="stylesheet">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
</head>

<body>
<div class="container">
    <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
            <div class="col-6 text-left">
                <h5 class="blog-header-logo text-dark">Radek G.</h5>
            </div>
            <div class="col-2 d-flex justify-content-end align-items-center">
                <form id="search" action="{% url 'blog:post_search' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="text" name="phrase" placeholder="Search for posts" class="form-control"
                           style="width: 140px" required>
                </form>
                <a class="text-muted" href="javascript:{document.getElementById('search').submit()}"
                   aria-label="Search">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                         stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img"
                         viewBox="0 0 24 24" focusable="false"><title>Search</title>
                        <circle cx="10.5" cy="10.5" r="7.5"/>
                        <path d="M21 21l-5.2-5.2"/>
                    </svg>
                </a>
            </div>
        </div>
    </header>

    <div class="jumbotron p-4 p-md-5 text-white rounded bg-dark">
        <div class="row">
            <div class="col-md-5 px-0">
                <h1 class="display-4 font-italic"><a href="{% url 'blog:post_list' %}" class="text-white"
                                                     style="text-decoration-line: none">My Blog</a></h1>
                <p class="lead my-3">This is my blog. I've written {% total_posts %} posts so far.</p>
                <a class="btn btn-sm btn-outline-secondary" href="{% url 'blog:post_feed' %}">Subscribe to my RSS
                    feed</a>
            </div>
            <div class="col-md-3 px-0">
                <br>
                <h3 class="display-8 font-italic">Latest posts</h3>
                {% show_latest_posts 3 %}
            </div>
            <div class="col-md-4 px-0">
                <br>
                <h3 class="display-8 font-italic">Most commented posts</h3>
                {% get_most_commented_posts as most_commented_posts %}
                <ul>
                    {% for post in most_commented_posts %}
                        <li>
                            <a href="{{ post.get_absolute_url }}" class="text-white"
                               style="font-size: 1.5em; text-decoration-line: none">{{ post.title }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>

    <div>
        {% block content %}
        {% endblock %}
    </div>
</div>
</body>
</html>

blog/templates/blog/pagination.html
<footer>
    <p>
        <nav class="blog-pagination">
            <h6>Page {{ page.number }} of {{ page.paginator.num_pages }}</h6>

            {% if page.has_previous %}
                <a class="btn btn-outline-primary" href="?page={{ page.previous_page_number }}">Previous</a>
            {% endif %}

            {% if not page.has_previous %}
                <a class="btn btn-outline-secondary disabled" href="" tabindex="-1" aria-disabled="true">Previous</a>
            {% endif %}

            {% if page.has_next %}
                <a class="btn btn-outline-primary" href="?page={{ page.next_page_number }}">Next</a>
            {% endif %}

            {% if not page.has_next %}
                <a class="btn btn-outline-secondary disabled" href="#" tabindex="-1" aria-disabled="true">Next</a>
            {% endif %}
        </nav>
    </p>
</footer>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}
{% block content %}
    <div class="no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative"
         style="padding-left: 5%; padding-top: 2%;padding-bottom: 2%">

        <h1>{{ post.title }}</h1>
        <p class="text-muted">Tags:
            <strong>
                {% for tag in post.tags.all %}
                    <a href="{% url 'blog:post_list_by_tag' tag.slug %}" class="text-primary">{{ tag.name }}</a>
                    {% if not forloop.last %}, {% endif %}
                {% endfor %}
            </strong>
        </p>
        <p class="date">
            Published {{ post.publish }} by {{ post.author }}
        </p>
        {{ post.body|markdown }}
        <span><a class="btn btn-outline-primary" href="{% url "blog:post_share" post.id %}">Share this post</a></span>
    </div>

    <h2 class="font-italic">Similar post{{ similar_posts.count|pluralize }}</h2>
    <br>
    {% for post in similar_posts %}
        <ul>
            <li><a href="{{ post.get_absolute_url }}" class="text-dark">{{ post.title }}</a></li>
        </ul>
    {% empty %}
        Similar posts not found
        <br>
    {% endfor %}
    <hr>
    <br>

    {% with comments.count as total_comments %}
        <h2 class="font-italic">{{ total_comments }} comment{{ total_comments|pluralize }}</h2>
    {% endwith %}
    <br>

    {% for comment in comments %}
        <div style="padding: 15px">
            <p class="text-muted"><strong>Comment {{ forloop.counter }} by {{ comment.name }}
                on {{ comment.created }}</strong></p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>There are no comments yet.</p>
    {% endfor %}
    <hr>
    <br>
    {% if new_comment %}
        <h2 class="font-italic">Your comment has been added.</h2>
        <p><a href="{{ post.get_absolute_url }}">Add</a> another one</p>
        <br>
        <br>
    {% else %}
        <h2 class="font-italic">Add a new comment</h2>
        <form class="form-group" method="post">
            {% for comment in comment_form %}
                <div style="padding-bottom: 10px">
                    {{ comment.label }}:
                    <br>
                    {{ comment }}
                    <br>
                </div>
            {% endfor %}
            {% csrf_token %}
            <p><input class="btn btn-outline-primary" type="submit" value="Add comment"></p>
        </form>
    {% endif %}
{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}" class="text-white"
               style="font-size: 1.5em; text-decoration-line: none">{{ post.title }} </a>
        </li>
    {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}My Blog{% endblock %}

{% block content %}
    <h1 class="display-4 pb-1 mb-4 font-italic border-bottom">Recent posts</h1>
    {% if tag %}
        <p><h2>Posts tagged with "{{ tag.name }}"</h2>
        <strong><a href="{% url 'blog:post_list' %}" class="btn btn-outline-primary"
        >Go back</a> </strong>
        </p>
    {% endif %}
    <hr>
    <div class="row mb-2">

        {% for post in posts %}
            <div class="col-md-6">
                <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative"
                     style="min-height: 93%">
                    <div class="col p-4 d-flex flex-column position-static">
                        <p class="text-muted">Tags:
                            <strong>
                                {% for tag in post.tags.all %}
                                    <a href="{% url 'blog:post_list_by_tag' tag.slug %}"
                                       class="text-primary">{{ tag.name }}</a>
                                    {% if not forloop.last %}, {% endif %}
                                {% endfor %}
                            </strong>
                        </p>
                        <h3 class="mb-0">{{ post.title }}</h3>
                        <div class="mb-1 text-muted">{{ post.publish|date:"M j" }}</div>
                        <p class="mb-auto">{{ post.body|truncatewords_html:20|markdown }}</p>
                        <a href="{{ post.get_absolute_url }}" class="stretched-link">Continue reading</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <hr>

    {% include "blog/pagination.html" with page=page_obj %}
{% endblock %}

blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% block title %}Search{% endblock %}
{% block content %}
    <div class="no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative"
         style="padding-left: 5%; padding-top: 2%; padding-bottom: 2%">

        <h1 class="font-italic">Posts containing "{{ phrase }}"</h1>
        <h3>Found {{ total_results }} result{{ total_results|pluralize }}</h3>
        <br>
        {% for post in searched_posts %}
            <ul>
                <li><h4><a href="{{ post.get_absolute_url }}" class="text-dark">{{ post.title }}</a></h4>
                    {{ post.body|truncatewords:5 }}</li>
                <br>
            </ul>
        {% empty %}
            <p>There are no results for your query.</p>
        {% endfor %}
    </div>
{% endblock %}

blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}

{% block title %}Share a post{% endblock %}

{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>"{{ post.title }}" was successfully sent to {{ cd.to }}.</p>
        <a href="{% url 'blog:post_list' %}">Return to homepage</a>
    {% else %}
        <h1 class="font-italic">Share "{{ post.title }}" by email</h1>
        <form action="." method="post">
            {% for field in form %}
                {% if not forloop.last %}
                    <div style="padding-bottom: 10px">
                        {{ field.label }}:
                        <br>
                        {{ field }}
                        <br>
                    </div>
                {% endif %}
            {% endfor %}
            {% csrf_token %}
            <p><input type="submit" class="btn btn-outline-primary" value="Send e-mail"></p>
        </form>
    {% endif %}
{% endblock %}